name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: set up JDK 11.0.5
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.5
    - name: Build with Gradle
      run: ./gradlew :frontend:android:buildNeeded :frontend:android:bundle --full-stacktrace
      env:
        CI: true
        JAVA_TOOL_OPTIONS: "-Xms256m -Xmx1280m -XX:MaxMetaspaceSize=350m -XX:+HeapDumpOnOutOfMemoryError"
        GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx1536m -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError" -Dorg.gradle.daemon=false -Dorg.gradle.parallel=true -Dorg.gradle.workers.max=2 -Dkotlin.incremental=false -Dkotlin.compiler.execution.strategy=in-process'
        GPR_USER: niqo01
        GPR_API_KEY: ${{ secrets.GITHUB_TOKEN }}
    - name: Aggregate test results
      run: |
            mkdir -p build/reports/junit
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp --parents {} build/reports/junit/ \;
      if: always()
    - name: Archive production Android artifacts
      uses: actions/upload-artifact@v1
      with:
        name: android-dist
        path: frontend/android/build/outputs/
      if: always()
    - name: Archive Android lint report
      uses: actions/upload-artifact@v1
      with:
        name: android-lint
        path: frontend/android/build/reports/lint-results.html
      if: always()
    - name: Archive commit timestamp
      uses: actions/upload-artifact@v1
      with:
        name: commit-timestamp
        path: build/commit-timestamp.txt
      if: always()
    - name: Archive build reports
      uses: actions/upload-artifact@v1
      with:
        name: build-reports
        path: build/reports/
      if: always()
